const restData = [
  {
    id: "239799",
    name: "Hira Sweets",
    cloudinaryImageId: "lnitzq4fbnw76ofplm2w",
    locality: "Opposite Metro Pillar",
    areaName: "Kirti Nagar",
    costForTwo: "₹400 for two",
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Continental",
      "Bakery",
      "Street Food",
      "Sweets",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.3,
    veg: true,
    parentId: "5155",
    avgRatingString: "4.3",
    totalRatingsString: "5K+",
  },
  {
    id: "239799",
    name: "Hira Sweets",
    cloudinaryImageId: "lnitzq4fbnw76ofplm2w",
    locality: "Opposite Metro Pillar",
    areaName: "Kirti Nagar",
    costForTwo: "₹400 for two",
    cuisines: [
      "North Indian",
      "South Indian",
      "Chinese",
      "Continental",
      "Bakery",
      "Street Food",
      "Sweets",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4.3,
    veg: true,
    parentId: "5155",
    avgRatingString: "4.3",
    totalRatingsString: "5K+",
  },
  {
    id: "20055",
    name: "Subway",
    cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
    locality: "Karol Bagh",
    areaName: "Patel Nagar, Connaught Place",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4.3,
    parentId: "2",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
  },
  {
    id: "343711",
    name: "Chaayos Chai+Snacks=Relax",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/dfbcecfc-b380-4648-930a-b9b56b21e781_343711.JPG",
    locality: "Karol Bagh",
    areaName: "East Patel Nagar",
    costForTwo: "₹250 for two",
    cuisines: [
      "Bakery",
      "Beverages",
      "Chaat",
      "Desserts",
      "Home Food",
      "Italian",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "Sweets",
    ],
    avgRating: 4.4,
    parentId: "281782",
    avgRatingString: "4.4",
    totalRatingsString: "1K+",
  },
  {
    id: "651218",
    name: "McDonald's",
    cloudinaryImageId: "535fc9f9c135f7982317bbb6a64a1ffc",
    locality: "Vishal Cinema",
    areaName: "Rajouri Garden",
    costForTwo: "₹400 for two",
    cuisines: ["American", "Fast Food"],
    avgRating: 4.4,
    parentId: "630",
    avgRatingString: "4.4",
    totalRatingsString: "1K+",
  },
  {
    id: "129211",
    name: "Burger King",
    cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    locality: "Patel Rd",
    areaName: "Shadipur",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "American"],
    avgRating: 4.3,
    parentId: "166",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
  },
  {
    id: "228931",
    name: "FreshMenu",
    cloudinaryImageId: "6c4de7b481d3614370e5062b2f33e7d6",
    locality: "A Block",
    areaName: "Rajouri Garden",
    costForTwo: "₹250 for two",
    cuisines: [
      "Continental",
      "Chinese",
      "Oriental",
      "Asian",
      "Healthy Food",
      "Fast Food",
      "Indian",
      "Desserts",
    ],
    avgRating: 4.1,
    parentId: "398",
    avgRatingString: "4.1",
    totalRatingsString: "10K+",
  },
  {
    id: "263731",
    name: "Upwas Specials by Lunchbox",
    cloudinaryImageId: "jby8hnuqggusau5neolh",
    locality: "DDA Market",
    areaName: "Rajendra Place",
    costForTwo: "₹200 for two",
    cuisines: ["Biryani", "North Indian", "Desserts", "Beverages"],
    avgRating: 4.2,
    parentId: "21938",
    avgRatingString: "4.2",
    totalRatingsString: "100+",
  },
  {
    id: "336057",
    name: "Wendy's Burgers",
    cloudinaryImageId: "f1aa621021a2826088089b89842d4e7c",
    locality: "DDA Market",
    areaName: "Rajendra Place",
    costForTwo: "₹200 for two",
    cuisines: ["Burgers", "American", "Fast Food", "Snacks", "Beverages"],
    avgRating: 4.2,
    parentId: "972",
    avgRatingString: "4.2",
    totalRatingsString: "500+",
  },
];

export default restData;
